# Generated by Django 4.2.5 on 2023-09-17 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrganisasi',
            fields=[
                ('id_organisasi', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tahun', models.CharField(max_length=4)),
                ('urai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserNew',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('hak_akses', models.CharField(default='pegawai', max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ManyToManyField(blank=True, related_name='tri_set', to='auth.group')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_organisasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.masterorganisasi')),
                ('permissstions', models.ManyToManyField(blank=True, related_name='aldi_set', to='auth.permission')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
