# Generated by Django 4.2.5 on 2023-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
