# Generated by Django 4.2.5 on 2023-09-18 04:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usernew_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MasterKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_bidang', models.TextField(max_length=225)),
                ('urai_bidang', ckeditor.fields.RichTextField()),
                ('kd_program', models.TextField(max_length=225)),
                ('urai_program', ckeditor.fields.RichTextField()),
                ('kd_kegiatan', models.TextField(max_length=225)),
                ('urai_kegiatan', ckeditor.fields.RichTextField()),
                ('kd_subkegiatan', models.TextField(max_length=225)),
                ('urai_subkegiatan', ckeditor.fields.RichTextField()),
                ('pagu', models.TextField(max_length=225)),
                ('pagu_p', models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_lokasi', models.CharField(max_length=225)),
                ('urai', models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPegawai',
            fields=[
                ('nip', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=225)),
                ('golongan', models.CharField(max_length=225)),
                ('no_hp', models.CharField(max_length=225)),
                ('eselon', models.CharField(max_length=225)),
                ('alamat', models.CharField(max_length=225)),
                ('pangakat', models.TextField(max_length=225)),
                ('email', models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTahun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('status', models.BooleanField(default=False, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='masterorganisasi',
            name='tahun',
        ),
        migrations.AddField(
            model_name='masterorganisasi',
            name='kode_organisasi',
            field=models.CharField(default='none', max_length=225),
        ),
        migrations.AlterField(
            model_name='masterorganisasi',
            name='urai',
            field=models.CharField(max_length=225),
        ),
        migrations.CreateModel(
            name='MasterPengesah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rek', models.TextField(max_length=225)),
                ('nama_bank', models.TextField(max_length=225)),
                ('status', models.BooleanField(default=False, max_length=1)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.masterpegawai')),
            ],
        ),
    ]
