# Generated by Django 4.2.4 on 2023-09-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_masterpegawai_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpengesah',
            name='jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.masterjabatan'),
        ),
    ]
