# Generated by Django 4.2.4 on 2023-09-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_masterpengesah_jabatan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterPegawai',
        ),
    ]
