# Generated by Django 4.2.4 on 2023-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_masterpegawai'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=225)),
                ('nama', models.CharField(max_length=225)),
                ('golongan', models.CharField(max_length=225)),
                ('no_hp', models.CharField(max_length=225)),
                ('eselon', models.CharField(max_length=225)),
                ('alamat', models.CharField(max_length=225)),
                ('pangkat', models.TextField(max_length=225)),
                ('email', models.TextField(max_length=225)),
            ],
        ),
    ]
