# Generated by Django 4.2.4 on 2023-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_masterpegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpengesah',
            name='namax',
            field=models.CharField(default=False, max_length=225),
        ),
    ]
