# Generated by Django 4.2.4 on 2023-09-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_masterpengesah_namax_masterpengesah_idpeg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpengesah',
            name='idPeg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.masterpegawai'),
        ),
    ]
